# Generated by Django 4.2.11 on 2024-03-31 19:40

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('calculators', '0004_remove_variable_equation_equation_variables_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calculator',
            options={'ordering': ['calc_category', 'name'], 'verbose_name': 'Calculator', 'verbose_name_plural': 'Calculators'},
        ),
        migrations.AlterModelOptions(
            name='equation',
            options={'verbose_name': 'Equation', 'verbose_name_plural': 'Equations'},
        ),
        migrations.AlterModelOptions(
            name='variable',
            options={'verbose_name': 'Variable', 'verbose_name_plural': 'Variables'},
        ),
        migrations.AlterField(
            model_name='equation',
            name='name',
            field=models.CharField(default='test', help_text='Calculator name', max_length=72),
        ),
        migrations.AlterField(
            model_name='equation',
            name='variables',
            field=models.ManyToManyField(help_text='A known variable in this equation', to='calculators.variable'),
        ),
        migrations.AlterField(
            model_name='variable',
            name='val',
            field=models.FloatField(help_text="The variable's value", null=True),
        ),
        migrations.AddConstraint(
            model_name='calculator',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='calc_name_case_insensitive_unique', violation_error_message='Calculator Already Exists'),
        ),
    ]
